#端口号为8081
server:
  port: 8081
spring:
  application:
    #在服务中心的应用名称
    name: cloud-service
#禁止注册自己
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.center9001:9001/eureka
  instance:
    #显示主机名
    instance-id: cloud-dao
    #显示主机ip
    prefer-ip-address: false